### ISSUE TITLE
Remove the black background from the top menu

### ISSUE THREAD

**Issue by siman** [dappforce/dappforce-subsocial-ui#152]
![image](https://user-images.githubusercontent.com/153928/80223501-0a35ea80-8651-11ea-915b-24e89b6fcd68.png)

**Comment by subsocialdev** [comment]
Fixed here: https://github.com/dappforce/dappforce-subsocial-ui/commit/1f16cb8972ddb48fc32a2ec2b40ad597ba6a8d66
