### ISSUE TITLE
Bug: Three auth requests on Polkadot extension. Should be one

### ISSUE THREAD

**Issue by siman** [dappforce/dappforce-subsocial-ui#164]
**UPD**: One request removed, two left.

Two screenshots of the same modal:

![image](https://user-images.githubusercontent.com/153928/80345271-8eff4f00-8871-11ea-8c46-752f2558084f.png)
![image](https://user-images.githubusercontent.com/153928/80345308-9a527a80-8871-11ea-806c-1463b41b02fd.png)

**Comment by subsocialdev** [comment]
fixed
