### ISSUE TITLE
Show account's balance on account page and account preview

### ISSUE THREAD

**Issue by siman** [dappforce/dappforce-subsocial-ui#168]
A balance should be here:
![image](https://user-images.githubusercontent.com/153928/80420329-46807980-88e3-11ea-9012-48ce8506efd6.png)

and here:
![image](https://user-images.githubusercontent.com/153928/80420414-6748cf00-88e3-11ea-8ea5-cca1a851171c.png)

**Comment by subsocialdev** [comment]
Implemented here https://github.com/dappforce/dappforce-subsocial-ui/pull/184
